#!/usr/bin/env node
// Sync the loadable extension source tree to ./dist for quick bb-browser
// reloads. Run after any source change; bb-browser users keep the same
// "Load unpacked → dist/" mapping and just click "Reload" in chrome.
//
// Usage: node scripts/build-dist.mjs [--channel store|community-dev]

import { rmSync, mkdirSync, cpSync, existsSync, statSync, writeFileSync } from 'node:fs';
import { resolve, dirname, relative } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const dist = resolve(root, 'dist');
const CHANNELS = new Set(['store', 'community-dev']);
const DIST_EXCLUDED_FILES = new Set([
  'src/premium/content-filter/rules.json',
]);

// Same canonical shipping set used by the release zip,
// plus the M1 premium tree under src/.
const ITEMS = [
  '_locales',
  'icons',
  'lib',
  'src',
  'auth-callback.html',
  'auth-callback.js',
  'background.js',
  'bridge.js',
  'bookmark-menu.js',
  'content.js',
  'manifest.json',
  'popup.html',
  'popup.js',
  'popup-dashboard.js', // mock A tab router (also handles theme + nav events)
  'starchart.js',
  'styles.css',
];

function readChannel(argv) {
  const idx = argv.indexOf('--channel');
  const raw = idx >= 0 ? argv[idx + 1] : 'store';
  if (!CHANNELS.has(raw)) {
    throw new Error(`[build-dist] invalid --channel ${raw || '(missing)'}; expected store or community-dev`);
  }
  return raw;
}

function channelMarker(channel) {
  return `// Generated by scripts/build-dist.mjs. Source defaults to store.\n(function (root) {\n  'use strict';\n  const channel = '${channel}';\n  root.__XVM_BUILD_CHANNEL__ = channel;\n  root.__xvmBuildChannel = channel;\n  root.__xvmIsCommunityDevBuild = channel === 'community-dev';\n})(typeof globalThis !== 'undefined' ? globalThis : window);\n`;
}

function distFilter(srcPath) {
  const rel = relative(root, srcPath).replaceAll('\\', '/');
  return !DIST_EXCLUDED_FILES.has(rel);
}

function main() {
  const channel = readChannel(process.argv.slice(2));
  let cleanRoot = true;
  if (existsSync(dist)) {
    try {
      rmSync(dist, { recursive: true, force: true });
    } catch (err) {
      if (err?.code !== 'EBUSY') throw err;
      cleanRoot = false;
      console.warn('[build-dist] dist/ is locked, refreshing entries in place');
      for (const item of ITEMS) {
        rmSync(resolve(dist, item), { recursive: true, force: true });
      }
    }
  }
  mkdirSync(dist, { recursive: true });

  let copied = 0;
  for (const item of ITEMS) {
    const src = resolve(root, item);
    const dst = resolve(dist, item);
    if (!existsSync(src)) {
      console.warn(`[build-dist] skip missing: ${item}`);
      continue;
    }
    const st = statSync(src);
    if (st.isDirectory()) {
      cpSync(src, dst, { recursive: true, filter: distFilter });
    } else {
      if (!distFilter(src)) continue;
      cpSync(src, dst);
    }
    copied += 1;
  }
  writeFileSync(resolve(dist, 'src/build-channel.js'), channelMarker(channel));
  console.log(`[build-dist] synced ${copied} entries to dist/${cleanRoot ? '' : ' (in-place)'}`);
  console.log(`[build-dist] channel: ${channel}`);
  console.log(`[build-dist] chrome → load unpacked → ${dist}`);
}

main();
